# Generated by Django 6.0.4 on 2026-04-16 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=150)),
                ('documento_identidad', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El documento de identidad solo puede contener letras y números.', regex='^[0-9A-Za-z]+$')])),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono de contacto solo puede contener números.', regex='^\\d+$')])),
                ('tipo_solicitud', models.CharField(choices=[('academica', 'Académica'), ('administrativa', 'Administrativa'), ('tecnica', 'Técnica'), ('otra', 'Otra')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion_detallada', models.TextField()),
                ('fecha_solicitud', models.DateField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='solicitudes/')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
